name: Documentation
on:
  release:
    types: [created]
  workflow_dispatch:

concurrency:
  group: doc-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    env:
      NODE_OPTIONS: --openssl-legacy-provider

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init & Build
        uses: ./.github/actions/build

      - name: Pre-compile TOC
        run: pnpm predocs

      - name: Build vuepress docs
        run: pnpm docs:build

      # Build all examples (except for docgen-nuxt which needs to be sent to surge)
      - name: Build examples
        run: |
          cd examples
          for D in *; do
            if [ "$D" = "vuecli-noplugin" ]; then
              echo "Skipping $D in docs workflow due to index.html asset conflict"
              continue
            fi
            cd ..
            pnpm build "${D}" -- --ci
            cd examples
          done
          cd .. || exit 1

      # Move them to the docs (except for docgen-nuxt which needs to be sent to surge)
      - name: Move examples to docs
        run: |
          cd examples
          for D in *; do
            if [ "$D" = "vuecli-noplugin" ]; then
              continue
            fi
            mv "${D}"/dist ../docs/dist/"${D}"
          done || exit 1

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/dist

  deploy-docs:
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

